server:
  port: 8000

spring:
  application:
    name: mvc-apigateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: first-service
              uri: http://localhost:8081/
              predicates:
                - Path=/first-service/**
            - id: second-service
              uri: http://localhost:8082/
              predicates:
                - Path=/second-service/**