server:
  port: 8001

eureka:
  client:
    register-with-eureka: true
    prefer-ip-address: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: flux-apigateway-service
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: Spring Cloud Gateway WebFlux Global Filter
                preLogger: true
                postLogger: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/catalog-service/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/order-service/**
            - id: first-service
              uri: lb://first-service
              predicates:
                - Path=/first-service/**
              filters:
#                - AddRequestHeader=f-request, 1st-request-header-from-yaml
#                - AddResponseHeader=f-response, 1st-response-header-from-yaml
              - name: CustomFilter
            - id: second-service
              uri: lb://second-service
              predicates:
                - Path=/second-service/**
              filters:
#                - AddRequestHeader=s-request, 2nd-request-header-from-yaml
#                - AddResponseHeader=s-response, 2nd-response-header-from-yaml
                - name: CustomFilter
                - name: LoggingFilter
                  args:
                    BaseMessage: Hi, there!
                    preLogger: true
                    postLogger: true