server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git: # default
          uri: file://D:\\study\\framework\\spring-cloud\\my-toy-msa\\git-local-repo
          default-label: master