server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native # 또는 git
  cloud:
    config:
      server:
        native:
          search-locations: "file:///D:/study/framework/spring-cloud/my-toy-msa/local-repo"
        git: # default
#          url: file:///D:/study/framework/spring-cloud/my-toy-msa/git-local-repo
          uri: "https://github.com/joneconsulting/spring-cloud-config"  # 작가의 github repo에서 가져옴
          default-label: master
          # username: [username]
          # password: [password]

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - httptrace
          - busrefresh